### ISSUE TITLE
I'm confuses what am I missing 

### ISSUE THREAD

**Issue by Samirahajiragab** [Samirahajiragab/hear-me-oh-content#1]
What am I missing?

@hellachella
@jessjodoin

**Comment by JessJodoin** [comment]
What seems to be the problem?

**Comment by Samirahajiragab** [comment]
<img width="470" alt="image" src="https://user-images.githubusercontent.com/55094325/94952513-18b3e800-04b4-11eb-8a28-bcf55b76988b.png">

**Comment by JessJodoin** [comment]
Your nav should look like this:

```
  <header role="banner">
    <h1>The Mighty Sloth</h1>
    <img src="images/logo.svg" alt="The Mighty Sloth Logo" role="presentation">

    <nav role="navigation">
      <ol>
        <li><a href="#sloth">Sloth</a></li>
        <li><a href="#three-toed">Three-toed sloths</a></li>
      </ol>
    </nav>
  </header>
```

and each section with the `<h2>` should have a corresponding `id=""` tag so it jumps down to the content when clicked

**Comment by JessJodoin** [comment]
Also your <a> tags in each section should look like this (but with the content to match)

`<a href="https://en.wikipedia.org/wiki/Sloth" aria-label="Read more about sloths">Read more</a>`

**Comment by JessJodoin** [comment]
Oh! I almost forgot. 
Line 16 - you don’t need an `<i lang="ja">` tag here, remove it

**Comment by Samirahajiragab** [comment]
Still says the same think

**Comment by JessJodoin** [comment]
Can you commit so I can see the changes you made?

**Comment by Samirahajiragab** [comment]
I did it

**Comment by JessJodoin** [comment]
You still have an `<i>` tag surrounding the logo (line18), it needs to be removed.

You need the change the `<a>` tags to look like I mentioned before. Markbot is mad because your links aren’t leading to the right places. They all lead to the same place and are not unique, so someone using a screen reader would have a hard time knowing what the right link they want is. 

Copy these in place of your `<a>` tags

navigation `<a>` tags
`<a href="#sloth">Sloth</a>`
` <a href="#three-toed">Three-toed sloths</a>`

Sloths `<a>` tag
`<a href="https://en.wikipedia.org/wiki/Sloth" aria-label="Read more about sloths">Read more</a>`

Three-toed sloth `<a>` tag
`<a href="https://en.wikipedia.org/wiki/Three-toed_sloth" aria-label="Read more about three-toed sloths">Read more</a>`

Footer `<a>` tag
`<a href="https://en.wikipedia.org/wiki/Sloth">https://en.wikipedia.org/wiki/Sloth</a>`

**Comment by JessJodoin** [comment]
If this issue is resolved, could you close the issue? 😺
